
typedef struct PCM PCM;

typedef enum InitPCMStatus {
	SUCCESS,
	FAILED_ALLOCATE_MEMORY,
	FAILED_OPEN_PCM,
	FAILED_SET_ACCESS,
	FAILED_SET_CHANNELS,
	FAILED_SET_FORMAT,
	FAILED_SET_RATE,
	FAILED_SET_PARAMS,

} InitPCMStatus;

InitPCMStatus initPCM(PCM *pcm);
